# Generated by Django 3.2 on 2021-05-26 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Country name', max_length=250)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('symbol', models.CharField(blank=True, max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Display it in trips list / search results?')),
                ('featured', models.BooleanField(default=False, help_text='Display it on main/index page?')),
                ('image', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('name', models.CharField(blank=True, help_text='Guide name', max_length=250)),
                ('description', tinymce.models.HTMLField(blank=True, help_text='Text about this trip')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('youtube_video_url', models.URLField(blank=True, help_text='Link/URL to youtube video, copy it from browser address bar', max_length=250)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=250)),
                ('phone2', models.CharField(blank=True, help_text='Phone number #2', max_length=250)),
                ('facebook', models.CharField(blank=True, help_text='Facebook page URL', max_length=250)),
                ('instagram', models.CharField(blank=True, help_text='Instagram page URL', max_length=250)),
                ('telegram', models.CharField(blank=True, help_text='Telegram user', max_length=250)),
                ('whatsapp', models.CharField(blank=True, help_text='WhatsApp user', max_length=250)),
                ('skype', models.CharField(blank=True, help_text='Skype user', max_length=250)),
                ('index', models.TextField(blank=True, null=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Language guide able speak on', max_length=250)),
                ('slug', models.SlugField(default='')),
                ('flag_icon', models.CharField(blank=True, help_text='URL to Language flag icon, use: https://iconarchive.com/show/all-country-flag-icons-by-custom-icon-design.html', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, help_text='Site title / main name', max_length=250)),
                ('slogan', models.CharField(blank=True, help_text='Slogan, marketing phrase', max_length=250)),
                ('main_text', tinymce.models.HTMLField(blank=True, help_text='Text to be displayed on main (index) page under H1 title')),
                ('main_text_bottom', tinymce.models.HTMLField(blank=True, help_text='Text to be displayed on main (index) page under content, before footer')),
                ('footer_text', tinymce.models.HTMLField(blank=True, help_text='Text to be displayed in footer')),
                ('meta_keywords', models.TextField(blank=True, help_text='Keywords for META tag')),
                ('meta_description', models.TextField(blank=True, help_text='Description for META tag')),
                ('register_text', tinymce.models.HTMLField(blank=True, help_text='Text to be displayed on guide registration page')),
                ('booking_help', tinymce.models.HTMLField(blank=True, help_text='Text to be displayed on booking page')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(blank=True, help_text='User name (maybe anonymous)', max_length=250)),
                ('text', tinymce.models.HTMLField(blank=True, help_text='Review text')),
                ('rating', models.CharField(choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='5', max_length=1)),
                ('isModerated', models.BooleanField(default=False, help_text='Is this review should be shown')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.guide')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Region name', max_length=250)),
                ('slug', models.SlugField()),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.country')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Location name', max_length=250)),
                ('slug', models.SlugField()),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.country')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.region')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='languages',
            field=models.ManyToManyField(blank=True, to='trips.Language'),
        ),
        migrations.AddField(
            model_name='guide',
            name='locations',
            field=models.ManyToManyField(blank=True, to='trips.Location'),
        ),
        migrations.AddField(
            model_name='guide',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.region'),
        ),
        migrations.AddField(
            model_name='guide',
            name='user',
            field=models.ForeignKey(blank=True, default=None, help_text='User, author/owner of this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(blank=True, help_text='User name', max_length=250)),
                ('preferredDate', models.DateField(help_text='Preferred date', null=True)),
                ('preferredTime', models.TimeField(help_text='Preferred time', null=True)),
                ('text', tinymce.models.HTMLField(blank=True, help_text='Special wishes text')),
                ('numberOfParticipants', models.CharField(blank=True, help_text='Number of participants in tour', max_length=250)),
                ('phone', models.CharField(blank=True, help_text='Phone number', max_length=250)),
                ('isConfirmed', models.BooleanField(default=False, help_text='Does booking was confirmed by guide')),
                ('isCanceled', models.BooleanField(default=False, help_text='Does booking was canceled by guide')),
                ('cancel_message', models.CharField(blank=True, help_text='Why booking was canceled?', max_length=250, null=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trips.guide')),
                ('user', models.ForeignKey(blank=True, default=None, help_text='User, who booked trip', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
