# Generated by Django 3.2 on 2021-05-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='isModerated',
            field=models.BooleanField(default=True, help_text='Is this review should be shown'),
        ),
    ]
