# Generated by Django 3.2 on 2021-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_review_ismoderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Is guide confirmed'),
        ),
    ]
