# Generated by Django 3.2 on 2021-05-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_guide_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('logins', models.IntegerField(default=0, help_text='Кількість логінів за день')),
                ('registers', models.IntegerField(default=0, help_text='Кількість логінів за день')),
            ],
        ),
    ]
