# Generated by Django 3.2 on 2021-05-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_statistic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='id',
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateField(auto_now_add=True, primary_key=True, serialize=False),
        ),
    ]
