# Generated by Django 3.2 on 2021-05-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20210531_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='bookings',
            field=models.IntegerField(default=0, help_text='Кількість бронювань за день'),
        ),
    ]
