# Generated by Django 3.2 on 2021-06-02 12:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_statistic_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('text', tinymce.models.HTMLField(help_text='Ваші зауваження, або побажання')),
            ],
        ),
    ]
