# Generated by Django 3.2 on 2021-06-04 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0008_savedguides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedguides',
            name='user',
            field=models.OneToOneField(blank=True, default=None, help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
