# Generated by Django 3.2 on 2021-06-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_alter_savedguides_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
