# Generated by Django 3.2 on 2021-06-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_alter_review_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(blank=True, help_text='Review text', max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_name',
            field=models.CharField(blank=True, help_text='User name (maybe anonymous)', max_length=50),
        ),
    ]
