# Generated by Django 3.2 on 2021-06-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0011_auto_20210606_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
