# Generated by Django 3.2 on 2021-06-14 22:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0012_alter_guide_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
