# Generated by Django 3.2 on 2021-06-18 18:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0014_alter_guide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
