# Generated by Django 3.2 on 2021-06-18 21:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0017_alter_guide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='numberOfParticipants',
            field=models.CharField(blank=True, help_text='Number of participants in tour', max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number', max_length=13),
        ),
        migrations.AlterField(
            model_name='booking',
            name='text',
            field=tinymce.models.HTMLField(blank=True, help_text='Special wishes text', max_length=250),
        ),
    ]
